### ISSUE TITLE
A failed test case

### ISSUE THREAD

**Issue by anhtranbk** [binhle74/mail-generator#1]
The following test case failed:

- template: `Hi {me}, welcome to {company}, bla bla !`
- params: name=NA, company=PrimeData
- expect: `Hi NA, welcome to PrimeData, bla bla !`
- actual Output: `Hi NA, welcome to PrimeData`

You should add the rest of the `template` to the `mailContent` as below:
```
    ...
        // Keep last character matched index to append substring into content
        lastCharMatchedIndex = phMatcher.end();
    }
    if (lastCharMatchedIndex < template.length()) {
        mailContent.append(template, lastCharMatchedIndex, template.length());
    }
    return mailContent.toString();
```

**Comment by binhle74** [comment]
Fix in PR https://github.com/binhle74/mail-generator/pull/2

**Comment by binhle74** [comment]
@anhtranbk It has been fixed, please checkout the latest changes
